Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%timeit matmul4(A,B,C)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[37], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_line_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mtimeit[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mmatmul4(A,B,C)[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/IPython/core/interactiveshell.py:2480[0m, in [0;36mInteractiveShell.run_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2478[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[1;32m   2479[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m-> 2480[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2482[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[1;32m   2483[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[1;32m   2484[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[1;32m   2485[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [0;32m/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/IPython/core/magics/execution.py:1185[0m, in [0;36mExecutionMagics.timeit[0;34m(self, line, cell, local_ns)[0m
[1;32m   1183[0m [38;5;28;01mfor[39;00m index [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m0[39m, [38;5;241m10[39m):
[1;32m   1184[0m     number [38;5;241m=[39m [38;5;241m10[39m [38;5;241m*[39m[38;5;241m*[39m index
[0;32m-> 1185[0m     time_number [38;5;241m=[39m [43mtimer[49m[38;5;241;43m.[39;49m[43mtimeit[49m[43m([49m[43mnumber[49m[43m)[49m
[1;32m   1186[0m     [38;5;28;01mif[39;00m time_number [38;5;241m>[39m[38;5;241m=[39m [38;5;241m0.2[39m:
[1;32m   1187[0m         [38;5;28;01mbreak[39;00m

File [0;32m/usr/share/miniconda3/envs/runenv/lib/python3.12/site-packages/IPython/core/magics/execution.py:173[0m, in [0;36mTimer.timeit[0;34m(self, number)[0m
[1;32m    171[0m gc[38;5;241m.[39mdisable()
[1;32m    172[0m [38;5;28;01mtry[39;00m:
[0;32m--> 173[0m     timing [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43minner[49m[43m([49m[43mit[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mtimer[49m[43m)[49m
[1;32m    174[0m [38;5;28;01mfinally[39;00m:
[1;32m    175[0m     [38;5;28;01mif[39;00m gcold:

File [0;32m<magic-timeit>:1[0m, in [0;36minner[0;34m(_it, _timer)[0m

[0;31mNameError[0m: name 'matmul4' is not defined

